### ISSUE TITLE
InitgPty missing in PAIN.008.001.02

### ISSUE THREAD

**Issue by Pablo849** [raphaelm/python-sepadd#7]
Hello, I am trying to make an import of SEPA debts for a bank in Spain with schema pain.008.001.02. It tells me in the errors that the identification of the creditor in the header is missing. I have been consulting the documentation of several banks and in all of them, it indicates that the InitgPty element must be added to it. I leave a link to the documentation of a couple of European banks.
https://businessbanking.bankofireland.com/fs/doc/wysiwyg/sepa-direct-debit-pain-008-001-02-xml-file-structure-july-2013.pdf
https://www.handelsbanken.com/shb/inet/icentsv.nsf/vlookuppics/a_filmformatbeskrivningar_fil_iso_20022_xml_pain_008_001_02_direct_debit/$file/iso_pain_008_001_02_direct_debit.pdf

 This element is also included in the message definitions on the web iso20022.org
https://www.iso20022.org/documents/messages/1_0_version/pain/schemas/pain.001.001.02.zip

**Comment by Pablo849** [comment]
Sorry for the confusion. Effectively, the InitgPty element is included in the generation of pain.008.001.02. The failure is due to the need to include the ID field of "PartyIdentification8". Would it be possible to add this field to the generation in the core of the package? Thank you.

**Comment by raphaelm** [comment]
Sure, feel free to prepare a patch :)

**Comment by chdecultot** [comment]
Hi, 
We have the same requirement in France so I just proposed a patch.
Thanks!
